name: Java CD

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: pull master
        uses: actions/checkout@v1
      - name: buil docker container
        run: ./gradlew jibDockerBuild
      - name: login to docker in image to github
        run:  docker login docker.pkg.github.com --username BLMir --password "${GITHUB_PSW}"
        env:  
          GITHUB_PSW: ${{ secrets.GITHUB_PUSH_CREDENTIALS }}
      - name : tag image docker
        run: docker tag trash-classifier:1.0-SNAPSHOT docker.pkg.github.com/blmir/trashrecognition/trash-classifier
      - name: push docker image to registry in github
        run:  docker push docker.pkg.github.com/blmir/trashrecognition/trash-classifier
  runing:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: login to docker registry in github
        run: docker login docker.pkg.github.com --username BLMir --password "${GITHUB_PSW_PULL}"
        env:  
          GITHUB_PSW_PULL: ${{ secrets.GITHUB_PULL_CREDENTIALS }}
      - name: pull image
        run: docker pull docker.pkg.github.com/blmir/trashrecognition/trash-classifier:latest
      - name: kill current container
        continue-on-error: true
        run: |
          docker stop backend
          docker rm backend
      - name: run image
        run: docker run --name=backend  -p 7000:7000 -d -v /var/www/BE/model:/tmp docker.pkg.github.com/blmir/trashrecognition/trash-classifier

