name: Java CD

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: pull master
        uses: actions/checkout@v1
      - name: buil shadowJar
        run: ./gradlew shadowJar
      - name: move jar
        run: mv build/libs/trash-classifier-1.0-SNAPSHOT-all.jar /var/www/BE
      - name: run the jar
        run: java -cp libtensorflow-1.14.0.jar:. -Djava.library.path=. -jar trash-classifier-1.0-SNAPSHOT-all.jar
