name: Machine learning process

on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "tensorflow==1.15"
        pip install --upgrade tensorflow-hub
        pip install tensorflow_estimator
    - name: copy dataset
      run: wget "http://ecotrash.site/dataset-03012020.tar" 
    - name: unzip tar file
      run: tar -xvf dataset-03012020.tar
    - name: download tensorflow hub
      run: curl -LO https://github.com/tensorflow/hub/raw/master/examples/image_retraining/retrain.py
    - name: run tensorflow 
      run: python retrain.py --image_dir dataset-03⁄01⁄2020
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_NAME }}
        password: ${{ secrets.VPS_PASS }}
        port: 22
        source: "output_graph.pb"
        target: "/var/www/BE"
