name: Machine learning process

on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "tensorflow>=2.0.0"
        pip install --upgrade tensorflow-hub
    - name: copy dataset
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        port: 22
        source: "/root/dataset-03012020.tar"
        target: "."

